apiVersion: v1
kind: Service
metadata:
  name: data-collector-service
  namespace: data-collectors
spec:
  type: NodePort
  selector:
    app: data-collector
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000