apiVersion: v1
kind: Service
metadata:
  name: data-collectors-service
  namespace: data-collectors
spec:
  type: NodePort
  selector:
    app: data-collectors
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 32352